apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: myconfigs.democontroller.github.com.liuyehcf
spec:
  group: democontroller.github.com.liuyehcf
  version: v1
  names:
    kind: MyConfig
    plural: myconfigs
    singular: myconfig
  scope: Namespaced
